AllCops:
  Rails:
    Enabled: true

  Exclude:
    - db/schema.rb
    - bin/**/*

Metrics/LineLength:
  Max: 128

Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AsciiComments:
  Enabled: false
